on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release to GitHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build v86
        run: make build/libv86.js useacpi=true

      - name: Release to GitHub
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: Latest Release
          automatic_release_tag: latest
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            build/*.js
            build/*.js.map
